batch-size: 32
coeff-search-increment: 10.0
coeff-search-max: 200.0
coeff-search-min: -200.0
constrained-softmax: false
data-cfg:
  bias-threshold: 0.4
  n-train: 800
  n-val: 1500
  neg-label: descriptive
  output-prefix: true
  pos-label: spatial
  target-concept: vision
  weighted-sample: false
debias-coeff: null
evaluate-top-n-layer: 5
filter-layer-pct: 0.05
intervention-method: constant
method: WMD
model-name: gpt2
optimize-coeff: true
save-dir: runs_vision_logit
score-mode: logit_margin
seed: 4238
use-cache: false
use-offset: false
