batch-size: 32
data-cfg:
  bias-threshold: 0.1
  n-train: 800
  n-val: 1000
  neg-label: descriptive
  output-prefix: true
  pos-label: spatial
  target-concept: vision
  weighted-sample: false
evaluate-top-n-layer: 5
filter-layer-pct: 0.05
method: WMD
model-name: Qwen/Qwen-1_8B-chat
save-dir: runs_vision
seed: 4238
use-cache: false
use-offset: true
