batch-size: 32
data-cfg:
  bias-threshold: 0.01
  n-train: 1500
  n-val: 1500
  neg-label: descriptive
  output-prefix: true
  pos-label: spatial
  target-concept: vision
  weighted-sample: false
evaluate-top-n-layer: 5
filter-layer-pct: 0.05
method: WMD
model-name: gpt2
save-dir: runs_vision
seed: 4238
use-cache: false
use-offset: false
