batch-size: 32
coeff-search-increment: 20.0
coeff-search-max: 80.0
coeff-search-min: -80.0
constrained-softmax: true
data-cfg:
  bias-threshold: 0.4
  n-train: 800
  n-val: 1000
  neg-label: descriptive
  output-prefix: true
  pos-label: spatial
  target-concept: vision
  weighted-sample: false
debias-coeff: null
evaluate-top-n-layer: 1
filter-layer-pct: 0.05
intervention-method: constant
method: WMD
model-name: gpt2
optimize-coeff: true
save-dir: runs_vision_prob_fast
score-mode: prob_diff
seed: 4238
use-cache: false
use-offset: false
